// Generated by CoffeeScript 1.6.3
(function() {
  var path, wikipedia;

  path = require('path');

  wikipedia = require(path.join(__dirname, '..', '..', 'node', 'wikipedia'));

  describe('Wikipedia', function() {
    it('shoule be defined', function() {
      return expect(wikipedia).toBeDefined();
    });
    return it('Should scrape starbucks', function() {
      var url;
      url = 'http://en.wikipedia.org/wiki/Starbucks';
      return runs(function() {
        return wikipedia.scrape(url, function(res) {
          console.log(res);
          return expect(res).toBeDefined();
        });
      });
    });
  });

}).call(this);

/*
//@ sourceMappingURL=wikipediaSpec.map
*/
