// Generated by CoffeeScript 1.6.3
(function() {
  var app, express, fs, lodash, path, projectsPath;

  path = require('path');

  fs = require('fs');

  lodash = require('lodash');

  projectsPath = path.join(__dirname, 'app', 'projects');

  express = require("express");

  app = express();

  app.set('view engine', 'ejs');

  app.use('/', express["static"](__dirname + '/app'));

  app.engine('html', require('ejs').renderFile);

  app.use(require('nodejs-fastload').loader('/l'));

  app.get('/wikipedia/build/:name', function(req, res) {
    return res.json({
      hello: 'world'
    });
  });

  app.get('/project/', function(req, res) {
    var projects;
    projects = fs.readdirSync(projectsPath);
    return res.json(projects);
  });

  app.get('/project/:name', function(req, res) {
    var audio, images, imagesDir, name, project, text, textFile;
    name = req.params.name;
    project = path.join(projectsPath, name);
    textFile = path.join(project, 'text.txt');
    imagesDir = path.join(project, 'images');
    audio = path.join('projects', name, 'audio.aiff.mp3');
    text = fs.readFileSync(textFile) + "";
    images = fs.readdirSync(imagesDir);
    return res.json({
      name: name,
      text: text,
      images: images,
      audio: audio
    });
  });

  app.listen(3000);

}).call(this);

/*
//@ sourceMappingURL=app.map
*/
