// Generated by CoffeeScript 1.11.1
(function() {
  "use strict";
  var controller;

  controller = function(scope, http, location) {
    var promise;
    promise = http({
      method: 'post',
      url: '/project/',
      data: {
        status: 'created'
      }
    });
    scope.by_name = '';
    return promise.success(function(result) {
      console.log(result);
      return scope.articles = result;
    });
  };

  angular.module("nodeExecuterApp").controller("MainCtrl", ['$scope', '$http', '$location', controller]);

}).call(this);

//# sourceMappingURL=main.js.map
