// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  var controller;

  controller = function($scope, $http) {
    var promise;
    promise = $http({
      method: 'get',
      url: '/project/'
    });
    return promise.success(function(result) {
      return $scope.articles = result;
    });
  };

  angular.module("nodeExecuterApp").controller("MainCtrl", controller);

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
