// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  var controller;

  controller = function(scope, http, location) {
    var exe;
    scope.wikipedia = '';
    scope.continus = false;
    scope.inprogress = false;
    exe = function(url, data) {
      var promise;
      scope.inprogress = true;
      promise = http({
        method: 'post',
        url: url,
        data: data
      });
      promise.success(function(result) {
        scope.inprogress = false;
        if (scope.continus && url.indexOf('random') > 0) {
          return scope.random();
        } else {
          return location.path('/');
        }
      });
      return promise.error(function(error) {
        scope.inprogress = false;
        return console.log(error);
      });
    };
    scope.process = function() {
      return exe('/build/url/', {
        url: scope.wikipedia
      });
    };
    scope.today = function() {
      return exe('/build/today/');
    };
    return scope.random = function() {
      return exe('/build/random/');
    };
  };

  angular.module('nodeExecuterApp').controller('NewCtrl', ['$scope', '$http', '$location', controller]);

}).call(this);

/*
//@ sourceMappingURL=new.map
*/
