// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  var controller;

  controller = function(root, scope, http, params, timeout, location) {
    var promise,
      _this = this;
    scope.project = {};
    scope.project.images = [];
    scope.pathOf = function(img) {
      return "projects/" + scope.project.name + "/images/" + img;
    };
    scope.isSvg = function(name) {
      var res;
      if (!name) {
        return false;
      }
      name = name.toLowerCase();
      res = _.str.endsWith(name, 'svg') || _.str.endsWith(name, 'gif');
      return res;
    };
    scope.remove = function() {
      var h;
      h = http({
        method: 'delete',
        url: "/project/" + scope.project.name
      });
      h.success(function(res) {
        console.log(res);
        return location.path('/');
      });
      return h.error(function(err) {
        return console.log(err);
      });
    };
    scope.markVideoed = function() {
      var h;
      h = http({
        method: 'post',
        url: "/project/" + scope.project.name,
        data: {
          status: 'videoed'
        }
      });
      h.success(function(res) {
        return console.log(res);
      });
      return h.error(function(err) {
        return console.log(err);
      });
    };
    promise = http({
      method: 'get',
      url: "/project/" + params.name
    });
    return promise.success(function(result) {
      var i, imgPath;
      scope.project = result;
      scope.project.images = _.filter(scope.project.images, function(image) {
        return !scope.isSvg(image.name);
      });
      i = 0;
      imgPath = scope.pathOf(scope.project.images[i++].name);
      $('.image img').attr('src', imgPath);
      timeout(function() {
        return fit($('.image img')[0], $('.image')[0], {
          vAlign: fit.CENTER
        });
      }, 1000);
      return scope.start = _.once(function() {
        var onAudio,
          _this = this;
        root.audioElement.src = "projects/" + scope.project.name + "/audio.aiff.mp3";
        root.audioElement.play();
        onAudio = function(event) {
          var changeImage, imgCount, scroll, scrollFn, splits, time;
          scope.duration = root.audioElement.duration;
          time = Math.floor(scope.duration * 1000 / scope.project.images.length);
          imgCount = scope.project.images.length;
          splits = imgCount < 5 ? imgCount : imgCount + 1;
          scroll = $('.text')[0].scrollHeight / splits;
          scrollFn = function() {
            var scrollTo;
            scrollTo = scroll * i;
            return $('.text').animate({
              scrollTop: scrollTo
            }, 1000);
          };
          changeImage = function() {
            var _this = this;
            if (i >= imgCount) {
              scrollFn();
              scope.markVideoed();
              return;
            }
            return $('.image img').fadeOut(500, function() {
              $('.image img').attr('src', scope.pathOf(scope.project.images[i].name));
              $('.image img').fadeIn(500);
              timeout(function() {
                return fit($('.image img')[0], $('.image')[0], {
                  vAlign: fit.CENTER
                });
              }, 80);
              scrollFn();
              i++;
              return scope.imageTimer = timeout(changeImage, time);
            });
          };
          return scope.imageTimer = timeout(changeImage, time);
        };
        root.audioElement.addEventListener("loadedmetadata", onAudio);
        return root.$on('$routeChangeStart', function() {
          timeout.cancel(scope.imageTimer);
          return root.audioElement.removeEventListener("loadedmetadata", onAudio);
        });
      });
    });
  };

  angular.module("nodeExecuterApp").controller("ProjectCtrl", ['$rootScope', '$scope', '$http', '$routeParams', '$timeout', '$location', controller]);

}).call(this);

/*
//@ sourceMappingURL=project.map
*/
