// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  var controller, yahoo_app_id;

  yahoo_app_id = 'vCu4FUjV34HSXktB0RHLPOjtgQPm3vnh0zchQcgX.ow8THogzl3Nta_rAC4-';

  controller = function(scope, http) {
    return scope.trendsFor = function(place) {
      var promise;
      promise = http.get('/trends/' + place);
      promise.success(function(res) {
        if (!res || !res.length) {
          console.log("No result for " + place);
          return scope.trends = [];
        } else {
          return scope.trends = res[0].trends;
        }
      });
      return promise.error(function(res) {
        return console.error(res);
      });
    };
  };

  angular.module('nodeExecuterApp').controller('TrendsCtrl', ['$scope', '$http', controller]);

}).call(this);

/*
//@ sourceMappingURL=trends.map
*/
