// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  var controller;

  controller = function(root, scope, http, params, timeout) {
    var promise,
      _this = this;
    scope.project = {};
    promise = http({
      method: 'get',
      url: "/project/" + params.name
    });
    return promise.success(function(result) {
      return scope.project = result;
    });
  };

  angular.module("nodeExecuterApp").controller('UploaddataCtrl', ['$rootScope', '$scope', '$http', '$routeParams', '$timeout', controller]);

}).call(this);

/*
//@ sourceMappingURL=uploaddata.map
*/
