// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  var controller;

  controller = function(scope, http, location) {
    var promise;
    promise = http({
      method: 'post',
      url: '/project/',
      data: {
        status: 'videoed'
      }
    });
    scope.by_name = '';
    return promise.success(function(result) {
      return scope.articles = result;
    });
  };

  angular.module("nodeExecuterApp").controller('VideoedCtrl', ['$scope', '$http', '$location', controller]);

}).call(this);

/*
//@ sourceMappingURL=videoed.map
*/
