// Generated by CoffeeScript 1.6.3
(function() {
  var Ping, Say, callback, lastResult, p, s;

  Ping = require('./ping').Ping;

  Say = require('./say').Say;

  p = new Ping();

  s = new Say();

  lastResult = null;

  callback = function(error, stdout, stderr) {
    if (error) {
      if (lastResult) {
        lastResult = false;
        return s.say('I am not online');
      }
    } else {
      if (!lastResult) {
        lastResult = true;
        return s.say('Horray, I am online');
      }
    }
  };

  setInterval(function() {
    return p.pingGoogle(callback);
  }, 5000);

}).call(this);

/*
//@ sourceMappingURL=run.map
*/
