// Generated by CoffeeScript 1.6.3
(function() {
  var Executer, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Executer = require('./executer').Executer;

  exports.Say = (function(_super) {
    __extends(Say, _super);

    function Say() {
      _ref = Say.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Say.prototype.say = function(something, callback) {
      var cmd;
      cmd = {
        name: 'say',
        command: "say " + something
      };
      return this.execute(cmd, callback);
    };

    return Say;

  })(Executer);

}).call(this);

/*
//@ sourceMappingURL=say.map
*/
