// Generated by CoffeeScript 1.6.3
(function() {
  var Executer, fs,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Executer = require('./executer').Executer;

  fs = require('fs');

  exports.Say = (function(_super) {
    __extends(Say, _super);

    Say.prototype.voices = {
      en: ['tom', 'ava']
    };

    function Say(defaultlang) {
      this.defaultlang = defaultlang;
      Say.__super__.constructor.call(this);
    }

    Say.prototype.voice = function(lang) {
      var arr;
      if (lang == null) {
        lang = this.defaultlang;
      }
      arr = lang ? this.voices[lang] : [];
      if (!arr.length) {
        return null;
      }
      return arr[Math.floor(Math.random() * arr.length)];
    };

    Say.prototype.say = function(something, callback) {
      var cmd, v;
      v = this.voice();
      cmd = {
        name: 'say',
        command: "say " + something
      };
      if (v) {
        cmd.command += " -v " + v;
      }
      return this.execute(cmd, callback);
    };

    Say.prototype.produce = function(audioFile, textFile, callback) {
      var audio, cmd, v,
        _this = this;
      audio = {};
      v = this.voice();
      audio.voice = v;
      cmd = {
        name: "say -o \"" + audioFile + "\" -f \"" + textFile + "\" ",
        command: "say -o \"" + audioFile + "\" -f \"" + textFile + "\" "
      };
      if (v) {
        cmd.command += "-v " + v + " ";
      }
      return this.execute(cmd, function() {
        return _this.toMp3(audioFile, function(file) {
          audio.file = file;
          return typeof callback === "function" ? callback(audio) : void 0;
        });
      });
    };

    Say.prototype.toMp3 = function(file, callback) {
      var _this = this;
      return fs.unlink("" + file + ".mp3", function() {
        var cmd;
        cmd = {
          name: "ffmpeg -i \"" + file + "\" -f mp3 -acodec libmp3lame -ab 192000 -ar 44100 \"" + file + "\".mp3",
          command: "ffmpeg -i \"" + file + "\" -f mp3 -acodec libmp3lame -ab 192000 -ar 44100 \"" + file + "\".mp3"
        };
        return _this.execute(cmd, function() {
          return typeof callback === "function" ? callback(file + ".mp3") : void 0;
        });
      });
    };

    return Say;

  })(Executer);

}).call(this);

/*
//@ sourceMappingURL=say.map
*/
