// Generated by CoffeeScript 1.11.1
(function() {
  var BEARER_TOKEN, CONSUMER_KEY, CONSUMER_SECRET, Say, _, jqueryify, jsdom, twitter, urls;

  twitter = require('twitter');

  _ = require('lodash');

  jsdom = require('jsdom');

  Say = require('./say');

  jqueryify = function(url, callback) {
    return jsdom.env({
      url: url,
      scripts: ["http://code.jquery.com/jquery-2.0.2.min.js"],
      done: callback
    });
  };

  CONSUMER_KEY = '7kLdyMV97dFlwsE5WPG7J8kzE';

  CONSUMER_SECRET = 'z0VKtLBM5GHDmnKnXj8wZUcQhnyVQ54a2YaIYYw8PNIaqymo0Q';

  BEARER_TOKEN = new Buffer("${CONSUMER_KEY}:${CONSUMER_SECRET}").toString('base64');

  urls = {
    'New York': 'https://trends24.in/united-states/new-york/~cloud',
    'California': 'https://trends24.in/united-states/san-francisco/~cloud',
    'London': 'https://trends24.in/united-kingdom/london/~cloud',
    'United States': 'https://trends24.in/united-states/~cloud'
  };

  exports.Twitter = (function() {
    function Twitter() {
      this.auth();
    }

    Twitter.prototype.auth = function() {
      console.info(BEARER_TOKEN);
      this.twit = new twitter({
        consumer_key: CONSUMER_KEY,
        consumer_secret: CONSUMER_SECRET,
        bearer_token: BEARER_TOKEN
      });
      return this.twit;
    };

    Twitter.prototype.trendsFor = function(woeid, callback) {
      return this.auth().get('trends/place.json', {
        id: woeid,
        exclude: true
      }, function(data) {
        console.log(data);
        return typeof callback === "function" ? callback(null, data) : void 0;
      });
    };

    Twitter.prototype.placeTrends = function(place, callback) {
      return jqueryify(urls[place], (function(_this) {
        return function(err, window) {
          var $, tags;
          $ = window.$;
          tags = _.map($('ol#cloud-ol li a'), function(item) {
            return $(item).text().trim();
          });
          tags = _.filter(tags, function(tag) {
            return tag.indexOf('#') < 0;
          });
          console.log(tags);
          return callback(null, tags);
        };
      })(this));
    };

    return Twitter;

  })();

}).call(this);

//# sourceMappingURL=twitter.js.map
