// Generated by CoffeeScript 1.11.1
(function() {
  var twitter;

  twitter = require('twitter');

  exports.Twitter = (function() {
    function Twitter() {
      this.auth();
    }

    Twitter.prototype.auth = function() {
      this.twit = new twitter({
        consumer_key: 'RvbT0qnx25NLtoez7M9Lq2gBB',
        consumer_secret: 'fmpb8aDgI8hckvvGk7uPozM4C672HBGbbPATbbuJNU5bhiiYgR',
        access_token_key: '52365348-crI292ocHUqQShx0UvoSd4TqAIVZHJIMxxqfoPuQg',
        access_token_secret: 'pxpOgJm3FyDJOka1rkQ9okEQw0rDsXpITZ6EgkChCegaX'
      });
      return this.twit.login();
    };

    Twitter.prototype.trendsFor = function(woeid, callback) {
      this.auth();
      console.log(woeid);
      return this.twit.get('trends/place.json', {
        id: woeid
      }, function(data) {
        console.log(data);
        return typeof callback === "function" ? callback(null, data) : void 0;
      });
    };

    return Twitter;

  })();

}).call(this);

//# sourceMappingURL=twitter.js.map
