// Generated by CoffeeScript 1.6.3
(function() {
  var twitter;

  twitter = require('twitter');

  exports.Twitter = (function() {
    function Twitter() {
      this.twit = new twitter({
        consumer_key: 'KgLkVLRo23gI6qBxqT4jHg',
        consumer_secret: 'cZTlz992CZG8owjbe2DKwTf1WQEodxlcC2EkzJGvOI',
        access_token_key: '52365348-PcgjMasng4OOWYLBl09ofXTkfdCz2C9NRf9CPT7Ds',
        access_token_secret: 'rn6IY1UB5E57rWInDJcDsdTqakmPPPjCRUpO6BLNfyE1U'
      });
      this.twit.login();
    }

    Twitter.prototype.trendsFor = function(woeid, callback) {
      return this.twit.get('trends/place.json', {
        id: woeid
      }, function(data) {
        console.log(data);
        return typeof callback === "function" ? callback(null, data) : void 0;
      });
    };

    return Twitter;

  })();

}).call(this);

/*
//@ sourceMappingURL=twitter.map
*/
