// Generated by CoffeeScript 1.11.1
(function() {
  var YQL;

  YQL = require('yql');

  exports.Yahoo = (function() {
    var yahoo_app_id;

    function Yahoo() {}

    yahoo_app_id = 'vCu4FUjV34HSXktB0RHLPOjtgQPm3vnh0zchQcgX.ow8THogzl3Nta_rAC4-';

    Yahoo.prototype.woeid = function(place, callback) {
      var query, yql;
      query = "SELECT locations.woe.timezone.woeid FROM ugeo.geocode where text='" + place + "' and appname='" + yahoo_app_id + "'";
      console.log(query);
      yql = new YQL(query);
      return yql.exec(function(error, response) {
        var ret;
        if (error) {
          console.error(error);
        }
        ret = response.query.results.result[0].locations.woe.timezone.woeid;
        console.log(ret);
        return typeof callback === "function" ? callback(error, ret) : void 0;
      });
    };

    return Yahoo;

  })();

}).call(this);

//# sourceMappingURL=yahoo.js.map
