// Generated by CoffeeScript 1.6.3
(function() {
  var request;

  request = require("request");

  exports.Yahoo = (function() {
    var yahoo_app_id;

    function Yahoo() {}

    yahoo_app_id = 'vCu4FUjV34HSXktB0RHLPOjtgQPm3vnh0zchQcgX.ow8THogzl3Nta_rAC4-';

    Yahoo.prototype.woeid = function(place, callback) {
      var url;
      url = "http://where.yahooapis.com/v1/places.q('" + place + "')?format=json&appid=" + yahoo_app_id;
      return request(url, function(err, res, body) {
        return typeof callback === "function" ? callback(err, res) : void 0;
      });
    };

    return Yahoo;

  })();

}).call(this);

/*
//@ sourceMappingURL=yahoo.map
*/
