// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  angular.module('nodeExecuterApp').filter('str', function() {
    return function(input, method) {
      return _.str[method](input);
    };
  });

}).call(this);

/*
//@ sourceMappingURL=humanize.map
*/
