// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  var app;

  app = angular.module("nodeExecuterApp", []);

  app.config(function($routeProvider) {
    return $routeProvider.when("/", {
      templateUrl: "views/main.html",
      controller: "MainCtrl"
    }).when('/project/:name', {
      templateUrl: 'views/project.html',
      controller: 'ProjectCtrl'
    }).otherwise({
      redirectTo: "/"
    });
  });

}).call(this);

/*
//@ sourceMappingURL=app.map
*/
