// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  var controller;

  controller = function(scope) {};

  angular.module('nodeExecuterApp').directive('tabnav', function() {
    return {
      templateUrl: './views/directives/tabnav.html',
      restrict: 'E',
      scope: {
        selected: '@',
        filter: '='
      },
      controller: ['$scope', controller]
    };
  });

}).call(this);

/*
//@ sourceMappingURL=tabnav.map
*/
